version: "3.7"
services:
  db:
    container_name: db
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/etc/mysql/conf.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    expose:
      - 3306
    depends_on:
      - ubuntu

  php:
    container_name: php
    image: php:fpm
    volumes:
      - ./html:/var/www/html
    expose:
      - 9000
    depends_on:
      - db
      - ubuntu

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./html:/var/www/html/
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - php
      - db
      - ubuntu

  ubuntu:
    container_name: ubuntu
    build: ./
    volumes:
      - ./html:/var/www/html/
volumes:
  db_data:
